### ISSUE TITLE
merge_enrich_terms stops with scan() error

### ISSUE THREAD

**Issue by daskandalis** [abrionne/ViSEAGO#1]
I am using the code from the vignette on my own data. `createTopGOdata()` and `runTest()` are fine, but merging them fails. I tried, 

`
BP_sResults<-ViSEAGO::merge_enrich_terms(
    Input=list(
        condition=c("BP","classic")
    )
)
`

but R stops with the error,

`Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 3 elements`

**Comment by abrionne** [comment]
I'm sorry but ViSEAGO (1.1.3, last version available on https://forgemia.inra.fr/umr-boa/viseago) work fine...
May be , could you send me a personal email with your script and data, if you need more help.

Sincerely,

Aurélien,
