### ISSUE TITLE
failed to open url

### ISSUE THREAD

**Issue by susheelbhanu** [abrionne/ViSEAGO#2]
Hi, 

Thanks for a great tool. I'm trying to get annotations for Uniprot IDs, but am getting the following error:

```> myGENE2GO<-ViSEAGO::annotate("P0A9N4",Uniprot)
Error in download.file(paste("ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/",  :
  cannot open URL 'ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/P0A9N4/goa_P0A9N4.gaf.gz'
In addition: Warning message:
In download.file(paste("ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/",  :
  cannot open URL 'ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/P0A9N4/goa_P0A9N4.gaf.gz': FTP status was '550 Requested action not taken; file unavailable'
```

I did the following prior to running this:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ViSEAGO")
library(ViSEAGO)
Uniprot<-ViSEAGO::Uniprot2GO()
ViSEAGO::available_organisms(Uniprot)
```

Thank you for your help!
-Susheel

**Comment by abrionne** [comment]
Hi,


Thanks for your comment, I have update the connection method to uniprotkb.

You can install the new version on https://forgemia.inra.fr/umr-boa/viseago,
or later (in at least several hours) on bioconductor ViSEAGO devel using source package.

https://www.bioconductor.org/packages/devel/bioc/src/contrib/ViSEAGO_1.1.4.tar.gz<https://www.bioconductor.org/packages/devel/bioc/src/contrib/ViSEAGO_1.1.3.tar.gz>


Sincerely,

     ___________________

        Aurélien BRIONNE
      Ingénieur d'études biologiste en traitements de données
      aurelien.brionne@inra.fr
      INRAE - Centre Val de Loire
      UMR 0083: BOA
      Tel. : +33 (0)2 47 42 72 93
     ___________________
________________________________
De : Susheel Bhanu Busi <notifications@github.com>
Envoyé : samedi 8 février 2020 12:12
À : abrionne/ViSEAGO
Cc : Subscribed
Objet : [abrionne/ViSEAGO] failed to open url (#2)


Hi,

Thanks for a great tool. I'm trying to get annotations for Uniprot IDs, but am getting the following error:

Error in download.file(paste("ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/",  :
  cannot open URL 'ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/P0A9N4/goa_P0A9N4.gaf.gz'
In addition: Warning message:
In download.file(paste("ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/",  :
  cannot open URL 'ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/P0A9N4/goa_P0A9N4.gaf.gz': FTP status was '550 Requested action not taken; file unavailable'


I did the following prior to running this:

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ViSEAGO")
library(ViSEAGO)
Uniprot<-ViSEAGO::Uniprot2GO()
ViSEAGO::available_organisms(Uniprot)


Thank you for your help!
-Susheel

-
