### ISSUE TITLE
Problems with Arabidopsis Bioconductor annotation

### ISSUE THREAD

**Issue by Norbittner** [abrionne/ViSEAGO#3]
Hi,

thanks for this interesting tool. 

When trying to annotate the Arabidopsis file of the Bioconductor GO Annotations i'm getting the following error

```
myGENE2GO <- ViSEAGO::annotate("org.At.tair.db", Bioconductor)
'select()' returned 1:many mapping between keys and columns
Fehler in setnames(x, value) : 
  Can't assign 4 names to a 5 column data.table
```

testing Bioconductor annotation with the mouse files from your vignette worked perfect.

Thanks in advance

**Comment by abrionne** [comment]
Hi,

Thanks for your comment, I have update annotate method for prevent this error in ViSEAGO_1.1.6.

You can install the new version now using https://forgemia.inra.fr/umr-boa/viseago,
or later (in at least 24 hours) on bioconductor ViSEAGO devel using source package.
https://www.bioconductor.org/packages/devel/bioc/src/contrib/ViSEAGO_1.1.6.tar.gz<https://www.bioconductor.org/packages/devel/bioc/src/contrib/ViSEAGO_1.1.3.tar.gz>

Sincerely,


     __________________

        Aurélien BRIONNE
      Ingénieur d'études biologiste en traitements de données
      aurelien.brionne@inra.fr
      INRAE - Centre Val de Loire
      UMR 0083: BOA
      Tel. : +33 (0)2 47 42 72 93
     ___________________
________________________________
De : Norbert Bittner <notifications@github.com>
Envoyé : mercredi 12 février 2020 12:43
À : abrionne/ViSEAGO
Cc : Subscribed
Objet : [abrionne/ViSEAGO] Problems with Arabidopsis Bioconductor annotation (#3)


Hi,

thanks for this interesting tool.

When trying to annotate the Arabidopsis file of the Bioconductor GO Annotations i'm getting the following error

myGENE2GO <- ViSEAGO::annotate("org.At.tair.db", Bioconductor)
'select()' returned 1:many mapping between keys and columns
Fehler in setnames(x, value) :
  Can't assign 4 names to a 5 column data.table


testing Bioconductor annotation with the mouse files from your vignette worked perfect.

Thanks in advance

-

**Comment by Norbittner** [comment]
Great. Many thanks for the quick reply...
